services:
  alertle-v2:
    image: ghcr.io/deekerman/alertle-v2:latest
    container_name: alertle-v2
    pull_policy: always
    restart: unless-stopped
    environment:
      TZ: America/Toronto
      ALERTLE_CONFIG: /config/config.yaml
    ports:
      - "8888:8888"
    volumes:
      - ./alertle-v2:/config
      - alertle_data:/app/data

volumes:
  alertle_data:
